# Generated by Django 5.2.13 on 2026-04-11 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_payment"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.DeleteModel(
            name="Payment",
        ),
    ]
