# Generated by Django 5.2.13 on 2026-08-01 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_payment_stripe_payment_link_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="stripe_payment_link",
            field=models.URLField(
                blank=True,
                max_length=999,
                null=True,
                verbose_name="Ссылка на оплату Stripe",
            ),
        ),
    ]
