# Generated by Django 5.2.13 on 2026-04-15 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0003_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=10000.0, max_digits=10, verbose_name="цена"
            ),
        ),
    ]
